#!/bin/sh

#- Monitor Settings -#
primary_monitor="HDMI-1"
primary_monitor_resolution="1920x1080"
primary_monitor_position="0x0"
primary_monitor_rotate="normal"
secondary_monitor="DP-1"
secondary_monitor_resolution="1366x768"
secondary_monitor_position="1920x312"
secondary_monitor_rotate="normal"

# Monitor #
xrandr \
	--output "$primary_monitor" --primary \
	--mode "$primary_monitor_resolution" \
	--pos "$primary_monitor_position" \
	--rotate "$primary_monitor_rotate" \
	--output "$secondary_monitor" \
	--mode "$secondary_monitor_resolution" \
	--pos "$secondary_monitor_position" \
	--rotate "$secondary_monitor_rotate"
